version: '3'

services:
  reverse-proxy:
    # The official v2 Traefik docker image
    image: traefik:v2.2
    # Enables the web UI and tells Traefik to listen to docker
    command: --api.insecure=true --providers.docker
    ports:
      # The HTTP port
      - "80:80"
      # The Web UI (enabled by --api.insecure=true)
      - "8080:8080"
      #- "9000:9000"
    volumes:
      # So that Traefik can listen to the Docker events
      - /var/run/docker.sock:/var/run/docker.sock

  gitea:
    image: gitea/gitea:latest
    environment:
      - USER_UID=1000
      - USER_GID=1000
    restart: unless-stopped
    #networks:
    #  - gitea
    volumes:
      - ./data/gitea:/data
    ports:
      - "222:222"
        #depends_on:
        #- db
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.gitea.entrypoints=http"
      - "traefik.http.routers.gitea.rule=Host(`gitea.${DOMAIN}`)" 
        #- "traefik.http.middlewares.gitea-https-redirect.redirectscheme.scheme=https"
        #- "traefik.http.routers.gitea.middlewares=gitea-https-redirect"
        #- "traefik.http.routers.gitea-secure.entrypoints=https"
        #- "traefik.http.routers.gitea-secure.rule=Path(`/gitea`)"
        #- "traefik.http.routers.gitea-secure.tls=true"
        #- "traefik.http.routers.gitea-secure.tls.certresolver=http"
      - "traefik.http.routers.gitea.service=gitea"
      - "traefik.http.services.gitea.loadbalancer.server.port=3000"
        #- "traefik.docker.network=gitea"

  minio:
    image: minio/minio:latest
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    command: server /data
    restart: unless-stopped
    volumes:
      - ./mnt/data:/data
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.minio.entrypoints=http"
      - "traefik.http.routers.minio.rule=Host(`minio.${DOMAIN}`)" 
      - "traefik.http.routers.minio.service=minio"
      - "traefik.http.services.minio.loadbalancer.server.port=9000"

  elasticsearch:
    image: elasticsearch:7.7.0
    environment:
      - node.name=es01
      - cluster.name=es-docker-cluster
      - discovery.seed_hosts=es01
      - cluster.initial_master_nodes=es01
        #- bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms1024m -Xmx1024m"
    expose:
      - 9200
    ports:
      - "9200:9200"
    restart: unless-stopped
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.elasticsearch.entrypoints=http"
      - "traefik.http.routers.elasticsearch.rule=Host(`elasticsearch.${DOMAIN}`)" 
      - "traefik.http.routers.elasticsearch.service=elasticsearch"
      - "traefik.http.services.elasticsearch.loadbalancer.server.port=9200"

  kibana:
    image: kibana:7.7.0
    links:
      - "elasticsearch"
        #ports:
        #- "5601:5601"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.kibana.entrypoints=http"
      - "traefik.http.routers.kibana.rule=Host(`kibana.${DOMAIN}`)" 
      - "traefik.http.routers.kibana.service=kibana"
      - "traefik.http.services.kibana.loadbalancer.server.port=5601"

  registry:
    restart: always
    image: registry:2
    #ports:
    #- 5000:5000
    environment:
      REGISTRY_HTTP_SECRET: 123456
    volumes:
      - /path/data:/var/lib/registry
        #- /path/certs:/certs
      - /path/auth:/auth
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.registry.entrypoints=http"
      - "traefik.http.routers.registry.rule=Host(`registry.${DOMAIN}`)" 
      - "traefik.http.routers.registry.service=registry"
      - "traefik.http.services.registry.loadbalancer.server.port=5000"
